{
 "title": "LinuxOS Dashboard",
 "description": "Metric view designed for a single system since some graphs overlay multiple queries.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasouce", "query": "prometheus" },
   {
    "name": "windows_instance",
    "query": {
     "query": "label_values(win_system_System_Up_Time,host)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(system_uptime{host!=\"$windows_instance\"},host)"
    }
   },
   {
    "name": "disk_device",
    "label": "Disk Device",
    "query": {
     "query": "label_values(disk_used_percent{host=\"$instance\", path!~\"/boot|/run/snapd/ns/lxd.mnt|/boot/efi\"},device)"
    }
   },
   {
    "name": "interface",
    "label": "Interface",
    "query": {
     "query": "label_values(net_bytes_sent{host=\"$instance\"},interface)"
    }
   },
   {
    "name": "disk",
    "label": "Disk",
    "query": {
     "query": "label_values(diskio_reads{host=\"$instance\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_uptime{host=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_n_cpus{host=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - cpu_usage_idle{host=\"$instance\", cpu=\"cpu-total\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mem_used_percent{host=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Root FS used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_used_percent{host=\"$instance\",path=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load average",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load1{host=\"$instance\"}",
     "legendFormat": "load1m"
    },
    {
     "expr": "system_load5{host=\"$instance\"}",
     "legendFormat": "load5m"
    },
    {
     "expr": "system_load15{host=\"$instance\"}",
     "legendFormat": "load15m"
    }
   ]
  },
  {
   "title": "RAM capacity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mem_total{host=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk info",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "disk_total{host=\"$instance\",path!~\"/run/snapd/ns/lxd.mnt|/boot|/boot/efi\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - cpu_usage_idle{host=\"$instance\", cpu=\"cpu-total\"}",
     "legendFormat": "All CPUs"
    }
   ]
  },
  {
   "title": "CPU used (User level)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cpu_usage_user{host=\"$instance\", cpu!=\"cpu-total\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU used (System level)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cpu_usage_system{host=\"$instance\", cpu!=\"cpu-total\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  { "title": "RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "RAM used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mem_used_percent{host=\"$instance\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mem_used{host=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "mem_available{host=\"$instance\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "mem_total{host=\"$instance\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mem_swap_total{host=\"$instance\"} - mem_swap_free{host=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "mem_swap_free{host=\"$instance\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "mem_swap_total{host=\"$instance\"}",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Disk device: $disk_device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 }, "repeat": "disk_device" },
  {
   "title": "Used - $disk_device",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_used_percent{host=\"$instance\",device=\"$disk_device\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "$disk_device",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "disk_used{host=\"$instance\", device=\"$disk_device\"}",
     "legendFormat": "Used on {{path}}"
    },
    {
     "expr": "disk_free{host=\"$instance\", device=\"$disk_device\"}",
     "legendFormat": "Free on {{path}}"
    },
    {
     "expr": "disk_total{host=\"$instance\", device=\"$disk_device\"}",
     "legendFormat": "Total on {{path}}"
    }
   ]
  },
  { "title": "Disk IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(diskio_reads{host=\"$instance\", name=~\"$disk\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(diskio_writes{host=\"$instance\", name=~\"$disk\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "IOPS in-progress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "diskio_iops_in_progress{host=\"$instance\", name=~\"$disk\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Read throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(diskio_read_bytes{host=\"$instance\", name=~\"$disk\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Write throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(diskio_write_bytes{host=\"$instance\", name=~\"$disk\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Connection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "TCP connection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "netstat_tcp_established{host=\"$instance\"}",
     "legendFormat": "Established connection"
    }
   ]
  },
  {
   "title": "UDP connection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "netstat_udp_socket{host=\"$instance\"}",
     "legendFormat": "Active connection"
    }
   ]
  },
  { "title": "Network Interface: $interface", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 }, "repeat": "interface" },
  {
   "title": "Network throughput (byte) - $interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(net_bytes_sent{host=\"$instance\",interface=~\"$interface\"}[5m])",
     "legendFormat": "Sent"
    },
    {
     "expr": "irate(net_bytes_recv{host=\"$instance\",interface=~\"$interface\"}[5m])",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Network throughput (packet) - $interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(net_packets_sent{host=\"$instance\",interface=~\"$interface\"}[5m])",
     "legendFormat": "Sent"
    },
    {
     "expr": "irate(net_packets_recv{host=\"$instance\",interface=~\"$interface\"}[5m])",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Network errors - $interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "irate(net_err_out{host=\"$instance\",interface=~\"$interface\"}[5m])",
     "legendFormat": "Send errors"
    },
    {
     "expr": "irate(net_err_in{host=\"$instance\",interface=~\"$interface\"}[5m])",
     "legendFormat": "Receive errors"
    }
   ]
  },
  {
   "title": "Packet dropped - $interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(net_drop_out{host=\"$instance\",interface=~\"$interface\"}[5m])",
     "legendFormat": "Sent"
    },
    {
     "expr": "irate(net_drop_in{host=\"$instance\",interface=~\"$interface\"}[5m])",
     "legendFormat": "Received"
    }
   ]
  }
 ]
}