services:
    grafana:
        container_name: "grafana"
        image: "grafana/grafana-oss:11.6.2"
        restart: unless-stopped
        ports:
            - "3000:3000"
        environment:
            - GF_ENDPOINT=${GF_ENDPOINT}
            - GF_ADMIN_USER=${GF_ADMIN_USER}
            - GF_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD}
            - GF_INSTALL_PLUGINS=grafana-opensearch-datasource
            - OPENSEARCH_ADMIN_PASSWORD=${OPENSEARCH_ADMIN_PASSWORD}
        volumes:
            - grafana_data:/var/lib/grafana
            - ./config/grafana/datasources:/etc/grafana/provisioning/datasources
            - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
        networks:
            - monitoring_network
    victoriametrics:
        container_name: "victoria-metrics"
        image: "victoriametrics/victoria-metrics:v1.119.0"
        restart: unless-stopped
        command:
            - "--storageDataPath=/victoriametrics"
            - "--httpListenAddr=:8428"
            - "--maxLabelsPerTimeseries=100"
        ports:
            - "8428:8428"
        volumes:
            - victoriametrics_data:/victoriametrics
        networks:
            - monitoring_network

    opensearch-dashboards:
        container_name: "opensearch-dashboards"
        image: "public.ecr.aws/opensearchproject/opensearch-dashboards:2.19.1"
        ports:
            - "5601:5601"
        expose:
            - "5601"
        environment:
            OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
        networks:
            - monitoring_network
        depends_on:
            - opensearch
    opensearch:
        container_name: "opensearch"
        image: "public.ecr.aws/opensearchproject/opensearch:2.19.1"
        environment:
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "OPENSEARCH_JAVA_OPTS=-Xms1G -Xmx2G"
            - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_ADMIN_PASSWORD}
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        ports:
            - "9200:9200"
        volumes:
            - opensearch_data:/usr/share/opensearch/data
        networks:
            - monitoring_network
    logstash:
        container_name: "logstash"
        image: "public.ecr.aws/opensearchproject/logstash-oss-with-opensearch-output-plugin:8.9.0"
        environment:
            - "LS_JAVA_OPTS=-Xms1G -Xmx2G"
        ports:
            - "12345:12345"
        volumes:
            - ./config/logstash/logstash.conf:/logstash_dir/logstash.conf
        command: logstash -f /logstash_dir/logstash.conf
        networks:
            - monitoring_network
        depends_on:
            - opensearch

    wazuh.dashboard:
        image: "wazuh/wazuh-dashboard:4.12.0"
        hostname: "wazuh.dashboard"
        restart: always
        ports:
            - "5602:5602"
        environment:
            - INDEXER_USERNAME=admin
            - INDEXER_PASSWORD=${WAZUH_INDEXER_PASSWORD}
            - WAZUH_API_URL=https://wazuh-manager
            - DASHBOARD_USERNAME=kibanaserver
            - DASHBOARD_PASSWORD=kibanaserver
            - API_USERNAME=${WAZUH_API_USERNAME}
            - API_PASSWORD=${WAZUH_API_PASSWORD}
        volumes:
            - ./config/wazuh/wazuh_dashboard/opensearch_dashboards.yml:/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml

            - ./data/wazuh/wazuh_dashboard/wazuh.yml:/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml
            - ./data/wazuh/wazuh_indexer_ssl_certs/wazuh.dashboard.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem
            - ./data/wazuh/wazuh_indexer_ssl_certs/wazuh.dashboard-key.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard-key.pem
            - ./data/wazuh/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-dashboard/certs/root-ca.pem

            - wazuh-dashboard-config:/usr/share/wazuh-dashboard/data/wazuh/config
            - wazuh-dashboard-custom:/usr/share/wazuh-dashboard/plugins/wazuh/public/assets/custom
        depends_on:
            - wazuh.indexer
        links:
            - wazuh.indexer:wazuh.indexer
            - wazuh.manager:wazuh.manager
        networks:
            - monitoring_network

    wazuh.manager:
        image: "wazuh/wazuh-manager:4.12.0"
        hostname: "wazuh.manager"
        restart: always
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 655360
                hard: 655360
        ports:
            - "1514:1514"
            - "1515:1515"
            - "514:514/udp"
            - "55000:55000"
        environment:
            - INDEXER_URL=https://wazuh.indexer:9201
            - INDEXER_USERNAME=admin
            - INDEXER_PASSWORD=${WAZUH_INDEXER_PASSWORD}
            - FILEBEAT_SSL_VERIFICATION_MODE=full
            - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
            - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
            - SSL_KEY=/etc/ssl/filebeat.key
            - API_USERNAME=${WAZUH_API_USERNAME}
            - API_PASSWORD=${WAZUH_API_PASSWORD}
        volumes:
            - ./config/wazuh/wazuh_cluster/wazuh_manager.conf:/wazuh-config-mount/etc/ossec.conf

            - ./data/wazuh/wazuh_indexer_ssl_certs/root-ca-manager.pem:/etc/ssl/root-ca.pem
            - ./data/wazuh/wazuh_indexer_ssl_certs/wazuh.manager.pem:/etc/ssl/filebeat.pem
            - ./data/wazuh/wazuh_indexer_ssl_certs/wazuh.manager-key.pem:/etc/ssl/filebeat.key

            - wazuh_api_configuration:/var/ossec/api/configuration
            - wazuh_etc:/var/ossec/etc
            - wazuh_logs:/var/ossec/logs
            - wazuh_queue:/var/ossec/queue
            - wazuh_var_multigroups:/var/ossec/var/multigroups
            - wazuh_integrations:/var/ossec/integrations
            - wazuh_active_response:/var/ossec/active-response/bin
            - wazuh_agentless:/var/ossec/agentless
            - wazuh_wodles:/var/ossec/wodles
            - filebeat_etc:/etc/filebeat
            - filebeat_var:/var/lib/filebeat
        networks:
            - monitoring_network

    wazuh.indexer:
        image: "wazuh/wazuh-indexer:4.12.0"
        hostname: "wazuh.indexer"
        restart: always
        ports:
            - "9201:9201"
        environment:
            - "OPENSEARCH_JAVA_OPTS=-Xms1G -Xmx2G"
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        volumes:
            - ./config/wazuh/wazuh_indexer/wazuh.indexer.yml:/usr/share/wazuh-indexer/opensearch.yml

            - ./data/wazuh/wazuh_indexer/internal_users.yml:/usr/share/wazuh-indexer/opensearch-security/internal_users.yml
            - ./data/wazuh/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-indexer/certs/root-ca.pem
            - ./data/wazuh/wazuh_indexer_ssl_certs/wazuh.indexer-key.pem:/usr/share/wazuh-indexer/certs/wazuh.indexer.key
            - ./data/wazuh/wazuh_indexer_ssl_certs/wazuh.indexer.pem:/usr/share/wazuh-indexer/certs/wazuh.indexer.pem
            - ./data/wazuh/wazuh_indexer_ssl_certs/admin.pem:/usr/share/wazuh-indexer/certs/admin.pem
            - ./data/wazuh/wazuh_indexer_ssl_certs/admin-key.pem:/usr/share/wazuh-indexer/certs/admin-key.pem

            - wazuh-indexer-data:/var/lib/wazuh-indexer
        networks:
            - monitoring_network

networks:
    monitoring_network:
        name: "monitoring_network"
        ipam:
            config:
                - subnet: 172.18.1.0/24

volumes:
    grafana_data:
        driver: local
    victoriametrics_data:
        driver: local
    opensearch_data:
        driver: local
    wazuh-dashboard-config:
        driver: local
    wazuh-dashboard-custom:
        driver: local
    wazuh_api_configuration:
        driver: local
    wazuh_etc:
        driver: local
    wazuh_logs:
        driver: local
    wazuh_queue:
        driver: local
    wazuh_var_multigroups:
        driver: local
    wazuh_integrations:
        driver: local
    wazuh_active_response:
        driver: local
    wazuh_agentless:
        driver: local
    wazuh_wodles:
        driver: local
    filebeat_etc:
        driver: local
    filebeat_var:
        driver: local
    wazuh-indexer-data:
        driver: local
