services:
  generator:
    image: wazuh/wazuh-certs-generator:0.0.2
    hostname: wazuh-certs-generator
    volumes:
    - ./data/wazuh/wazuh_indexer_ssl_certs/:/certificates/
    - ./config/wazuh/certs.yml:/config/certs.yml
