datasources:
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    uid: victoriametrics
    editable: true
    isDefault: true
    jsonData:
        prometheusType: Prometheus
        prometheusVersion: 2.24.0
